[rospy.client][INFO] 2019-04-02 21:44:16,707: init_node, name[/depthtest], pid[900]
[xmlrpc][INFO] 2019-04-02 21:44:16,707: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-04-02 21:44:16,708: Started XML-RPC server [http://9fe54ba3caf9:44961/]
[rospy.init][INFO] 2019-04-02 21:44:16,708: ROS Slave URI: [http://9fe54ba3caf9:44961/]
[rospy.impl.masterslave][INFO] 2019-04-02 21:44:16,708: _ready: http://9fe54ba3caf9:44961/
[xmlrpc][INFO] 2019-04-02 21:44:16,709: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-04-02 21:44:16,709: Registering with master node http://localhost:11311
[rospy.init][INFO] 2019-04-02 21:44:16,809: registered with master
[rospy.rosout][INFO] 2019-04-02 21:44:16,809: initializing /rosout core topic
[rospy.rosout][INFO] 2019-04-02 21:44:16,851: connected to core topic /rosout
[rospy.simtime][INFO] 2019-04-02 21:44:16,853: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2019-04-02 21:44:16,857: Running depth Grabber
[rospy.internal][INFO] 2019-04-02 21:44:17,100: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-04-02 21:44:27,136: signal_shutdown [signal-2]
[rospy.internal][INFO] 2019-04-02 21:44:27,141: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2019-04-02 21:44:27,141: signal-2
[rospy.core][INFO] 2019-04-02 21:44:27,243: signal_shutdown [atexit]
[rospy.client][INFO] 2019-04-02 21:44:59,123: init_node, name[/depthtest], pid[927]
[xmlrpc][INFO] 2019-04-02 21:44:59,123: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-04-02 21:44:59,124: Started XML-RPC server [http://9fe54ba3caf9:36719/]
[rospy.init][INFO] 2019-04-02 21:44:59,124: ROS Slave URI: [http://9fe54ba3caf9:36719/]
[rospy.impl.masterslave][INFO] 2019-04-02 21:44:59,124: _ready: http://9fe54ba3caf9:36719/
[xmlrpc][INFO] 2019-04-02 21:44:59,124: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-04-02 21:44:59,125: Registering with master node http://localhost:11311
[rospy.init][INFO] 2019-04-02 21:44:59,224: registered with master
[rospy.rosout][INFO] 2019-04-02 21:44:59,225: initializing /rosout core topic
[rospy.rosout][INFO] 2019-04-02 21:44:59,228: connected to core topic /rosout
[rospy.simtime][INFO] 2019-04-02 21:44:59,229: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2019-04-02 21:44:59,234: Running depth Grabber
[rospy.internal][INFO] 2019-04-02 21:44:59,460: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2019-04-02 21:46:08,524: topic[/camera/depth/image_raw] adding connection to [http://9fe54ba3caf9:45133/], count 0
[rospy.internal][WARNING] 2019-04-02 21:46:15,413: Unknown error initiating TCP/IP socket to 9fe54ba3caf9:54369 (http://9fe54ba3caf9:45133/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-04-02 21:46:15,413: topic[/camera/depth/image_raw] removing connection to http://9fe54ba3caf9:45133/
[rospy.internal][INFO] 2019-04-02 21:48:35,730: topic[/camera/depth/image_raw] adding connection to [http://9fe54ba3caf9:37963/], count 0
[rospy.internal][WARNING] 2019-04-02 21:48:56,738: Unknown error initiating TCP/IP socket to 9fe54ba3caf9:43995 (http://9fe54ba3caf9:37963/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-04-02 21:48:56,738: topic[/camera/depth/image_raw] removing connection to http://9fe54ba3caf9:37963/
[rospy.core][INFO] 2019-04-02 21:49:29,119: signal_shutdown [signal-2]
[rospy.internal][INFO] 2019-04-02 21:49:29,124: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2019-04-02 21:49:29,124: signal-2
[rospy.core][INFO] 2019-04-02 21:49:29,288: signal_shutdown [atexit]
[rospy.client][INFO] 2019-04-02 21:49:30,943: init_node, name[/depthtest], pid[1020]
[xmlrpc][INFO] 2019-04-02 21:49:30,944: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-04-02 21:49:30,944: Started XML-RPC server [http://9fe54ba3caf9:33063/]
[rospy.impl.masterslave][INFO] 2019-04-02 21:49:30,944: _ready: http://9fe54ba3caf9:33063/
[rospy.init][INFO] 2019-04-02 21:49:30,944: ROS Slave URI: [http://9fe54ba3caf9:33063/]
[xmlrpc][INFO] 2019-04-02 21:49:30,945: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-04-02 21:49:30,945: Registering with master node http://localhost:11311
[rospy.init][INFO] 2019-04-02 21:49:31,045: registered with master
[rospy.rosout][INFO] 2019-04-02 21:49:31,045: initializing /rosout core topic
[rospy.rosout][INFO] 2019-04-02 21:49:31,048: connected to core topic /rosout
[rospy.simtime][INFO] 2019-04-02 21:49:31,050: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2019-04-02 21:49:31,054: Running depth Grabber
[rospy.internal][INFO] 2019-04-02 21:49:31,270: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2019-04-02 21:49:34,077: topic[/camera/depth/image_raw] adding connection to [http://9fe54ba3caf9:33217/], count 0
[rospy.internal][WARNING] 2019-04-02 21:49:48,331: Unknown error initiating TCP/IP socket to 9fe54ba3caf9:55305 (http://9fe54ba3caf9:33217/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-04-02 21:49:48,331: topic[/camera/depth/image_raw] removing connection to http://9fe54ba3caf9:33217/
[rospy.core][INFO] 2019-04-02 21:49:56,071: signal_shutdown [signal-2]
[rospy.internal][INFO] 2019-04-02 21:49:56,075: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2019-04-02 21:49:56,076: signal-2
[rospy.core][INFO] 2019-04-02 21:49:56,184: signal_shutdown [atexit]
[rospy.client][INFO] 2019-04-02 21:50:40,237: init_node, name[/depthtest], pid[1075]
[xmlrpc][INFO] 2019-04-02 21:50:40,237: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-04-02 21:50:40,238: Started XML-RPC server [http://9fe54ba3caf9:45453/]
[rospy.init][INFO] 2019-04-02 21:50:40,238: ROS Slave URI: [http://9fe54ba3caf9:45453/]
[rospy.impl.masterslave][INFO] 2019-04-02 21:50:40,238: _ready: http://9fe54ba3caf9:45453/
[xmlrpc][INFO] 2019-04-02 21:50:40,239: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-04-02 21:50:40,239: Registering with master node http://localhost:11311
[rospy.init][INFO] 2019-04-02 21:50:40,338: registered with master
[rospy.rosout][INFO] 2019-04-02 21:50:40,339: initializing /rosout core topic
[rospy.rosout][INFO] 2019-04-02 21:50:40,341: connected to core topic /rosout
[rospy.simtime][INFO] 2019-04-02 21:50:40,343: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2019-04-02 21:50:40,346: Running depth Grabber
[rospy.internal][INFO] 2019-04-02 21:50:40,572: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2019-04-02 21:51:13,077: topic[/camera/depth/image_raw] adding connection to [http://9fe54ba3caf9:45401/], count 0
[rospy.internal][WARNING] 2019-04-02 21:51:24,620: Unknown error initiating TCP/IP socket to 9fe54ba3caf9:60087 (http://9fe54ba3caf9:45401/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-04-02 21:51:24,620: topic[/camera/depth/image_raw] removing connection to http://9fe54ba3caf9:45401/
[rospy.core][INFO] 2019-04-02 21:52:42,454: signal_shutdown [signal-2]
[rospy.internal][INFO] 2019-04-02 21:52:42,459: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2019-04-02 21:52:42,459: signal-2
[rospy.core][INFO] 2019-04-02 21:52:42,567: signal_shutdown [atexit]
[rospy.client][INFO] 2019-04-02 21:54:05,558: init_node, name[/depthtest], pid[1130]
[xmlrpc][INFO] 2019-04-02 21:54:05,558: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-04-02 21:54:05,559: Started XML-RPC server [http://9fe54ba3caf9:41057/]
[rospy.init][INFO] 2019-04-02 21:54:05,559: ROS Slave URI: [http://9fe54ba3caf9:41057/]
[rospy.impl.masterslave][INFO] 2019-04-02 21:54:05,559: _ready: http://9fe54ba3caf9:41057/
[xmlrpc][INFO] 2019-04-02 21:54:05,559: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-04-02 21:54:05,560: Registering with master node http://localhost:11311
[rospy.init][INFO] 2019-04-02 21:54:05,659: registered with master
[rospy.rosout][INFO] 2019-04-02 21:54:05,659: initializing /rosout core topic
[rospy.rosout][INFO] 2019-04-02 21:54:05,662: connected to core topic /rosout
[rospy.simtime][INFO] 2019-04-02 21:54:05,663: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2019-04-02 21:54:05,665: Running depth Grabber
[rospy.internal][INFO] 2019-04-02 21:54:05,883: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2019-04-02 21:54:23,644: topic[/camera/depth/image_raw] adding connection to [http://9fe54ba3caf9:41743/], count 0
[rospy.internal][WARNING] 2019-04-02 21:54:29,383: Unknown error initiating TCP/IP socket to 9fe54ba3caf9:36269 (http://9fe54ba3caf9:41743/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-04-02 21:54:29,384: topic[/camera/depth/image_raw] removing connection to http://9fe54ba3caf9:41743/
[rospy.core][INFO] 2019-04-02 21:54:30,717: signal_shutdown [signal-2]
[rospy.internal][INFO] 2019-04-02 21:54:30,721: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2019-04-02 21:54:30,721: signal-2
[rospy.core][INFO] 2019-04-02 21:54:30,885: signal_shutdown [atexit]
[rospy.client][INFO] 2019-04-02 21:56:17,005: init_node, name[/depthtest], pid[1188]
[xmlrpc][INFO] 2019-04-02 21:56:17,005: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-04-02 21:56:17,005: Started XML-RPC server [http://9fe54ba3caf9:38999/]
[rospy.init][INFO] 2019-04-02 21:56:17,006: ROS Slave URI: [http://9fe54ba3caf9:38999/]
[rospy.impl.masterslave][INFO] 2019-04-02 21:56:17,006: _ready: http://9fe54ba3caf9:38999/
[xmlrpc][INFO] 2019-04-02 21:56:17,006: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-04-02 21:56:17,007: Registering with master node http://localhost:11311
[rospy.init][INFO] 2019-04-02 21:56:17,106: registered with master
[rospy.rosout][INFO] 2019-04-02 21:56:17,106: initializing /rosout core topic
[rospy.rosout][INFO] 2019-04-02 21:56:17,109: connected to core topic /rosout
[rospy.simtime][INFO] 2019-04-02 21:56:17,111: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2019-04-02 21:56:17,114: Running depth Grabber
[rospy.internal][INFO] 2019-04-02 21:56:17,321: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2019-04-02 21:56:28,839: topic[/camera/depth/image_raw] adding connection to [http://9fe54ba3caf9:35967/], count 0
[rospy.internal][WARNING] 2019-04-02 21:56:41,601: Unknown error initiating TCP/IP socket to 9fe54ba3caf9:53553 (http://9fe54ba3caf9:35967/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-04-02 21:56:41,601: topic[/camera/depth/image_raw] removing connection to http://9fe54ba3caf9:35967/
[rospy.core][INFO] 2019-04-02 21:57:08,277: signal_shutdown [signal-2]
[rospy.internal][INFO] 2019-04-02 21:57:08,282: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2019-04-02 21:57:08,282: signal-2
[rospy.core][INFO] 2019-04-02 21:57:08,414: signal_shutdown [atexit]
[rospy.client][INFO] 2019-04-02 21:57:41,420: init_node, name[/depthtest], pid[1243]
[xmlrpc][INFO] 2019-04-02 21:57:41,420: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-04-02 21:57:41,420: Started XML-RPC server [http://9fe54ba3caf9:42821/]
[rospy.init][INFO] 2019-04-02 21:57:41,421: ROS Slave URI: [http://9fe54ba3caf9:42821/]
[rospy.impl.masterslave][INFO] 2019-04-02 21:57:41,421: _ready: http://9fe54ba3caf9:42821/
[xmlrpc][INFO] 2019-04-02 21:57:41,421: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-04-02 21:57:41,421: Registering with master node http://localhost:11311
[rospy.init][INFO] 2019-04-02 21:57:41,521: registered with master
[rospy.rosout][INFO] 2019-04-02 21:57:41,521: initializing /rosout core topic
[rospy.rosout][INFO] 2019-04-02 21:57:41,523: connected to core topic /rosout
[rospy.simtime][INFO] 2019-04-02 21:57:41,524: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2019-04-02 21:57:41,526: Running depth Grabber
[rospy.internal][INFO] 2019-04-02 21:57:41,750: topic[/camera/depth/image_raw] adding connection to [http://9fe54ba3caf9:40151/], count 0
[rospy.internal][INFO] 2019-04-02 21:57:41,802: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][WARNING] 2019-04-02 21:57:52,753: Unknown error initiating TCP/IP socket to 9fe54ba3caf9:59637 (http://9fe54ba3caf9:40151/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-04-02 21:57:52,753: topic[/camera/depth/image_raw] removing connection to http://9fe54ba3caf9:40151/
[rospy.core][INFO] 2019-04-02 21:58:35,484: signal_shutdown [signal-2]
[rospy.internal][INFO] 2019-04-02 21:58:35,488: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2019-04-02 21:58:35,488: signal-2
[rospy.core][INFO] 2019-04-02 21:58:35,652: signal_shutdown [atexit]
[rospy.client][INFO] 2019-04-02 21:58:36,762: init_node, name[/depthtest], pid[1298]
[xmlrpc][INFO] 2019-04-02 21:58:36,762: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-04-02 21:58:36,763: Started XML-RPC server [http://9fe54ba3caf9:39803/]
[rospy.impl.masterslave][INFO] 2019-04-02 21:58:36,763: _ready: http://9fe54ba3caf9:39803/
[rospy.init][INFO] 2019-04-02 21:58:36,763: ROS Slave URI: [http://9fe54ba3caf9:39803/]
[xmlrpc][INFO] 2019-04-02 21:58:36,764: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-04-02 21:58:36,764: Registering with master node http://localhost:11311
[rospy.init][INFO] 2019-04-02 21:58:36,864: registered with master
[rospy.rosout][INFO] 2019-04-02 21:58:36,864: initializing /rosout core topic
[rospy.rosout][INFO] 2019-04-02 21:58:36,866: connected to core topic /rosout
[rospy.simtime][INFO] 2019-04-02 21:58:36,868: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2019-04-02 21:58:36,872: Running depth Grabber
[rospy.internal][INFO] 2019-04-02 21:58:37,083: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2019-04-02 21:59:04,386: topic[/camera/depth/image_raw] adding connection to [http://9fe54ba3caf9:40541/], count 0
[rospy.internal][WARNING] 2019-04-02 21:59:12,011: Unknown error initiating TCP/IP socket to 9fe54ba3caf9:54381 (http://9fe54ba3caf9:40541/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-04-02 21:59:12,011: topic[/camera/depth/image_raw] removing connection to http://9fe54ba3caf9:40541/
[rospy.core][INFO] 2019-04-02 21:59:15,988: signal_shutdown [signal-2]
[rospy.internal][INFO] 2019-04-02 21:59:15,992: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2019-04-02 21:59:15,993: signal-2
[rospy.core][INFO] 2019-04-02 21:59:16,109: signal_shutdown [atexit]
[rospy.client][INFO] 2019-04-02 22:01:13,715: init_node, name[/depthtest], pid[1354]
[xmlrpc][INFO] 2019-04-02 22:01:13,715: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-04-02 22:01:13,715: Started XML-RPC server [http://9fe54ba3caf9:39067/]
[rospy.init][INFO] 2019-04-02 22:01:13,716: ROS Slave URI: [http://9fe54ba3caf9:39067/]
[rospy.impl.masterslave][INFO] 2019-04-02 22:01:13,716: _ready: http://9fe54ba3caf9:39067/
[xmlrpc][INFO] 2019-04-02 22:01:13,716: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-04-02 22:01:13,717: Registering with master node http://localhost:11311
[rospy.init][INFO] 2019-04-02 22:01:13,816: registered with master
[rospy.rosout][INFO] 2019-04-02 22:01:13,816: initializing /rosout core topic
[rospy.rosout][INFO] 2019-04-02 22:01:13,819: connected to core topic /rosout
[rospy.simtime][INFO] 2019-04-02 22:01:13,821: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2019-04-02 22:01:13,824: Running depth Grabber
[rospy.internal][INFO] 2019-04-02 22:01:14,063: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2019-04-02 22:01:24,099: topic[/camera/depth/image_raw] adding connection to [http://9fe54ba3caf9:34163/], count 0
[rospy.internal][ERROR] 2019-04-02 22:01:30,193: Unable to initiate TCP/IP socket to 9fe54ba3caf9:39075 (http://9fe54ba3caf9:34163/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/camera/depth/image_raw] from [TCPROS connection on port 39075 to [172.17.0.2:50060 on socket 3]] [/depthtest].

[rospy.internal][WARNING] 2019-04-02 22:01:31,195: Unknown error initiating TCP/IP socket to 9fe54ba3caf9:39075 (http://9fe54ba3caf9:34163/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-04-02 22:01:31,195: topic[/camera/depth/image_raw] removing connection to http://9fe54ba3caf9:34163/
[rospy.core][INFO] 2019-04-02 22:01:35,628: signal_shutdown [signal-2]
[rospy.internal][INFO] 2019-04-02 22:01:35,632: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2019-04-02 22:01:35,633: signal-2
[rospy.core][INFO] 2019-04-02 22:01:36,248: signal_shutdown [atexit]
[rospy.client][INFO] 2019-04-02 22:02:05,926: init_node, name[/depthtest], pid[1409]
[xmlrpc][INFO] 2019-04-02 22:02:05,927: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-04-02 22:02:05,927: Started XML-RPC server [http://9fe54ba3caf9:38431/]
[rospy.init][INFO] 2019-04-02 22:02:05,927: ROS Slave URI: [http://9fe54ba3caf9:38431/]
[rospy.impl.masterslave][INFO] 2019-04-02 22:02:05,927: _ready: http://9fe54ba3caf9:38431/
[xmlrpc][INFO] 2019-04-02 22:02:05,928: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-04-02 22:02:05,928: Registering with master node http://localhost:11311
[rospy.init][INFO] 2019-04-02 22:02:06,028: registered with master
[rospy.rosout][INFO] 2019-04-02 22:02:06,028: initializing /rosout core topic
[rospy.rosout][INFO] 2019-04-02 22:02:06,031: connected to core topic /rosout
[rospy.simtime][INFO] 2019-04-02 22:02:06,032: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2019-04-02 22:02:06,036: Running depth Grabber
[rospy.internal][INFO] 2019-04-02 22:02:06,243: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2019-04-02 22:02:23,362: topic[/camera/depth/image_raw] adding connection to [http://9fe54ba3caf9:33393/], count 0
[rospy.internal][WARNING] 2019-04-02 22:02:32,042: Unknown error initiating TCP/IP socket to 9fe54ba3caf9:58281 (http://9fe54ba3caf9:33393/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-04-02 22:02:32,042: topic[/camera/depth/image_raw] removing connection to http://9fe54ba3caf9:33393/
[rospy.core][INFO] 2019-04-02 22:02:35,067: signal_shutdown [signal-2]
[rospy.internal][INFO] 2019-04-02 22:02:35,072: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2019-04-02 22:02:35,072: signal-2
[rospy.core][INFO] 2019-04-02 22:02:35,180: signal_shutdown [atexit]
[rospy.client][INFO] 2019-04-02 22:02:36,321: init_node, name[/depthtest], pid[1464]
[xmlrpc][INFO] 2019-04-02 22:02:36,322: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-04-02 22:02:36,322: Started XML-RPC server [http://9fe54ba3caf9:37415/]
[rospy.init][INFO] 2019-04-02 22:02:36,322: ROS Slave URI: [http://9fe54ba3caf9:37415/]
[rospy.impl.masterslave][INFO] 2019-04-02 22:02:36,322: _ready: http://9fe54ba3caf9:37415/
[xmlrpc][INFO] 2019-04-02 22:02:36,323: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-04-02 22:02:36,323: Registering with master node http://localhost:11311
[rospy.init][INFO] 2019-04-02 22:02:36,423: registered with master
[rospy.rosout][INFO] 2019-04-02 22:02:36,423: initializing /rosout core topic
[rospy.rosout][INFO] 2019-04-02 22:02:36,426: connected to core topic /rosout
[rospy.simtime][INFO] 2019-04-02 22:02:36,427: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2019-04-02 22:02:36,430: Running depth Grabber
[rospy.internal][INFO] 2019-04-02 22:02:36,646: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-04-02 22:02:57,883: signal_shutdown [signal-2]
[rospy.internal][INFO] 2019-04-02 22:02:57,888: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2019-04-02 22:02:57,888: signal-2
[rospy.core][INFO] 2019-04-02 22:02:58,020: signal_shutdown [atexit]
[rospy.client][INFO] 2019-04-02 22:02:58,818: init_node, name[/depthtest], pid[1480]
[xmlrpc][INFO] 2019-04-02 22:02:58,819: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-04-02 22:02:58,819: Started XML-RPC server [http://9fe54ba3caf9:42575/]
[rospy.impl.masterslave][INFO] 2019-04-02 22:02:58,819: _ready: http://9fe54ba3caf9:42575/
[rospy.init][INFO] 2019-04-02 22:02:58,819: ROS Slave URI: [http://9fe54ba3caf9:42575/]
[xmlrpc][INFO] 2019-04-02 22:02:58,820: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-04-02 22:02:58,820: Registering with master node http://localhost:11311
[rospy.init][INFO] 2019-04-02 22:02:58,920: registered with master
[rospy.rosout][INFO] 2019-04-02 22:02:58,920: initializing /rosout core topic
[rospy.rosout][INFO] 2019-04-02 22:02:58,923: connected to core topic /rosout
[rospy.simtime][INFO] 2019-04-02 22:02:58,925: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2019-04-02 22:02:58,929: Running depth Grabber
[rospy.internal][INFO] 2019-04-02 22:02:59,125: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2019-04-02 22:03:01,200: topic[/camera/depth/image_raw] adding connection to [http://9fe54ba3caf9:34521/], count 0
[rospy.internal][ERROR] 2019-04-02 22:03:06,203: Unable to initiate TCP/IP socket to 9fe54ba3caf9:56085 (http://9fe54ba3caf9:34521/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/camera/depth/image_raw] from [TCPROS connection on port 56085 to [172.17.0.2:48612 on socket 10]] [/depthtest].

[rospy.internal][WARNING] 2019-04-02 22:03:07,205: Unknown error initiating TCP/IP socket to 9fe54ba3caf9:56085 (http://9fe54ba3caf9:34521/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-04-02 22:03:07,205: topic[/camera/depth/image_raw] removing connection to http://9fe54ba3caf9:34521/
[rospy.core][INFO] 2019-04-02 22:03:12,964: signal_shutdown [signal-2]
[rospy.internal][INFO] 2019-04-02 22:03:12,968: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2019-04-02 22:03:12,969: signal-2
[rospy.core][INFO] 2019-04-02 22:03:13,584: signal_shutdown [atexit]
